[package]
name = "holodeck"
version = "0.1.0"
edition = "2024"

[features]
scanner = ["pokedetect"]

[dependencies]
iced.workspace = true
iced.features = ["tokio", "canvas", "image", "debug"]

iced_palace.workspace = true
iced_palace.features = ["geometry"]

pokedetect.workspace = true
pokedetect.optional = true

serde.workspace = true
serde.features = ["derive"]

tokio.workspace = true
tokio.features = ["fs"]

anywho.workspace = true
bytes.workspace = true
dirs.workspace = true
function.workspace = true
futures-util.workspace = true
image.workspace = true
log.workspace = true
num-traits.workspace = true
pokebase.workspace = true
reqwest.workspace = true
ron.workspace = true
tracing-subscriber.workspace = true

[build-dependencies]
iced_fontello.workspace = true

[lints]
workspace = true

[workspace]
members = ["pokebase", "pokebase/core", "pokedetect"]

[workspace.lints.rust]
rust_2018_idioms = "deny"

[workspace.lints.clippy]
single-component-path-imports = "allow"
too-many-arguments = "allow"
large-enum-variant = "allow"

[workspace.dependencies]
pokebase.path = "./pokebase"
pokebase-core.path = "./pokebase/core"
pokedetect.path = "./pokedetect"

anywho = "0.1.2"
bytes = "1"
dirs = "6"
flate2 = "1"
function = "0.2"
futures-util = "0.3"
iced = "0.15.0-dev"
iced_fontello = "0.15.0-dev"
iced_palace = "0.15.0-dev"
image = "0.25"
leptess = "0.14"
log = "0.4"
num-traits = "0.2"
opencv = "0.95"
reqwest = "0.12"
ron = "0.10"
serde = "1"
serde_json = "1"
thiserror = "1"
tokio = "1"
tokio-stream = "0.1"
tracing-subscriber = "0.3"

[patch.crates-io]
iced.git = "https://github.com/iced-rs/iced.git"
iced.rev = "4255f613b887c3362214edd128acb8d2722bd0de"

iced_core.git = "https://github.com/iced-rs/iced.git"
iced_core.rev = "4255f613b887c3362214edd128acb8d2722bd0de"

iced_widget.git = "https://github.com/iced-rs/iced.git"
iced_widget.rev = "4255f613b887c3362214edd128acb8d2722bd0de"

iced_palace.git = "https://github.com/hecrj/iced_palace.git"
iced_palace.rev = "7b908e7e636837baa40879d569363b5d87f27a80"

iced_fontello.git = "https://github.com/hecrj/iced_fontello.git"
iced_fontello.rev = "e3652a7f9048f99d3ca85ff3f11b3c61cfa391d6"

# For testing new bleeding edge iced features
# iced.path = "../iced"
# iced_core.path = "../iced/core"
# iced_widget.path = "../iced/widget"
# iced_palace.path = "../iced-rs/palace"
