[package]
name = "pokedetect"
version = "0.1.0"
edition = "2024"
description = "A library for detecting Pokémon TCG cards from a video stream"
license = "MIT"

[dependencies]
anywho.workspace = true
bytes.workspace = true
image.workspace = true
leptess.workspace = true
log.workspace = true
tokio.workspace = true
tokio-stream.workspace = true

opencv.workspace = true
opencv.features = ["clang-runtime"]

[dev-dependencies]
iced.version = "0.14"
iced.features = ["tokio", "image", "debug"]

tracing-subscriber.workspace = true

[lints]
workspace = true
